// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for ios - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WLV-FpSPAcD9tggwH7Q3uAmqY-Kuz7Q',
    appId: '1:240502408472:android:5d5daa8dd3fc75b7b90a6d',
    messagingSenderId: '240502408472',
    projectId: 'bamis-app-28485',
    storageBucket: 'bamis-app-28485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HbwFemqRIekGNO-ngnG2r57vyHSuMoY',
    appId: '1:240502408472:ios:3f4fed9dbd6dcd8fb90a6d',
    messagingSenderId: '240502408472',
    projectId: 'bamis-app-28485',
    storageBucket: 'bamis-app-28485.firebasestorage.app',
    iosBundleId: 'com.example.bamis',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxt2OZLB1enZ_-iCbp-zW940mL_8PBGE',
    appId: '1:240502408472:web:3df143e96d4f9e7db90a6d',
    messagingSenderId: '240502408472',
    projectId: 'bamis-app-28485',
    authDomain: 'bamis-app-28485.firebaseapp.com',
    storageBucket: 'bamis-app-28485.firebasestorage.app',
    measurementId: 'G-JWE2GHTF4E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HbwFemqRIekGNO-ngnG2r57vyHSuMoY',
    appId: '1:240502408472:ios:b51d20894c76a6c2b90a6d',
    messagingSenderId: '240502408472',
    projectId: 'bamis-app-28485',
    storageBucket: 'bamis-app-28485.firebasestorage.app',
    iosBundleId: 'bd.gov.bamis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBxt2OZLB1enZ_-iCbp-zW940mL_8PBGE',
    appId: '1:240502408472:web:a9fa8f3c3ab8e5a9b90a6d',
    messagingSenderId: '240502408472',
    projectId: 'bamis-app-28485',
    authDomain: 'bamis-app-28485.firebaseapp.com',
    storageBucket: 'bamis-app-28485.firebasestorage.app',
    measurementId: 'G-XJDJ21XGCG',
  );

}