import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'Bamis',

      'tab_home': 'Home',
      'tab_agri': 'Agri-Hub',
      'tab_community': 'Community',
      'tab_profile': 'Profile',

      'dashboard': 'Dashboard',
      'dashboard_today_weather': 'Today\'s Weather',
      'dashboard_rainfall': 'Rainfall',
      'dashboard_humidity': 'Humidity',
      'dashboard_wind': 'Wind Speed',
      'dashboard_take_a_look': 'Take a look',
      'dashboard_my_crops': 'MY CROPS',
      'dashboard_view_all': 'View All',
      'dashboard_weather_forecast': 'Weather\nForecast',
      'dashboard_weather_alert': 'Weather\nAlert',
      'dashboard_flood_forecast': 'Flood\nForecast',
      'dashboard_crop_advisory': 'Crop\nAdvisory',
      'dashboard_pest_disease': 'Disease\nAlert',
      'dashboard_pest_disease_information': 'Disease\nInformation',
      'dashboard_task_reminder': 'Task\nReminder',
      'dashboard_advisory_bulletin': 'Advisory\nBulletin',
      'dashboard_online_library': 'Online\nLibrary',
      'dashboard_farm_metrics': 'Farm\nMetrics',
      'dashboard_stage_status': 'Stage Status',
      'dashboard_plantation': 'Plantation',
      'dashboard_stage_duration': 'Stage Duration',
      'dashboard_no_crops_found': 'You did not add any crops yet!',
      'dashboard_special_bulletin': 'Special Bulletin',
      'dashboard_mycrops_promo': "You didn't add any crops yet!",
      'dashboard_time_good_morning': "Good Morning",
      'dashboard_time_good_noon': "Good Noon",
      'dashboard_time_good_afternoon': "Good Afternook",
      'dashboard_time_good_evening': "Good Evening",
      'dashboard_time_good_night': "Good Night",
      'dashboard_sidebar_important_video': "Important Videos",
      'dashboard_sidebar_contact_us': "Contact Us",
      'dashboard_sidebar_faq': "FAQ",
      'dashboard_sidebar_logout': "Logout",
      'dashboard_snack_one_title': "Warning",
      'dashboard_snack_one_message': "This is stage is started yet. Please wait till this stage will appear.",
      'learn_more': "Learn more >",

      'weather_forecast': 'Weather Forecast',
      'wf_title': 'Weather Forecast',
      'wf_subtitle': 'Weather forecast for next 10 days',
      'wf_temp': 'Temparature',
      'wf_rf': 'Rainfall',
      'wf_rh': 'Humidity',
      'wf_wind': 'Wind Speed',

      'weather_alert': 'Weather Alert',
      'flood_forecast': 'Flood Forecast',

      'all_application': "All Application",

      'profile': 'Profile',
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_language': 'Language',
      'profile_language_select': 'Select Language',
      'profile_logout': 'Logout',
      'profile_logout_text': 'Logging out? We will be here when you are back!',

      'elibrary_title': 'Online Library',

      'scan': 'Scan',
      'title': 'Disease Detection',
      'wait': 'Please wait...',
      'select_crop': 'Select Crop',
      'select_photo': 'No photo selected, Please select or capture one phone!',
      'detect_disease_pest': 'Detect Disease & Pest',
      'disease_name': 'Disease Name',
      'scientific_name': 'Scientific Name',
      'pathogen': 'Pathogen',
      'virus': 'Virus',
      'bacteria': 'Bacteria',
      'deficiency': 'Deficiency',
      'additional': 'Additional',
      'fungi': 'Fungi',
      'insect': 'Insect',
      'mite': 'Mite',
      'weed': 'Weed',
      'others': 'Others',
      'can_also_found': 'Can also be found in',
      'potato': "Potato",
      'tomato': "Tomato",
      'rice': "Rice",
      'preventive_measures': "Preventive Measures",
      'symptoms': "Symptoms",
      'symptoms_short': "Symptoms Short",
      'treatment_chemical': "Treatment Chemical",
      'treatment_organic': "Treatment Organic",
      'trigger': "Trigger",

      'add_mycrop_title': "Add New Crop",
      'add_mycrop_select_crop': "Select Crop",
      'add_mycrop_select_location': "Select Location",
      'add_mycrop_select_plantation_date': "Select Plantation Date",
      'add_mycrop_submit': "Add New Crop",
      'add_mycrop_delete': "Delete",

      'mycrop_advisory_title': "Crop Advisory",
      'mycrop_advisory_promo': "Select particular crop to get specific advisory",
      'mycrop_advisory_stage_title': "Crop Stages",
      'mycrop_advisory_stage_promo': "Stage-by-stage recommendation for",
      'mycrop_disease_title': "Crop Disease",
      'mycrop_disease_promo': "Select particular crop to get specific disease advisory",
      'mycrop_disease_stage_title': "Crop Disease",
      'mycrop_disease_stage_promo': "Stage-by-stage recommendation for",

      'community_title': "Community",
      'community_promot': "Welcome to BAMIS community",
      'community_post_add_title': "Add new community post",

      'agrihub_get_cultivation_tips': "Get Cultivation Tips",

      'pda_title': 'Pest & Disease Information',
      'pda_select_crop': 'Select crop',
      'pda_view_all': 'View All',
      'pda_scientific_name': 'Scientific name',
      'pda_pathogen_name': 'Pathogen name',
      'pda_symptoms': 'Symptoms',
      'pda_preventive_measure': 'Preventive measure',
      'pda_organic_control': 'Organic control',
      'pda_chemical_control': 'Chemical control',
      'pda_what_caused_it': 'What caused_it',

      'notification_title': "Notifications",

      'task_reminder_title': "Task Reminder",
      'task_reminder_promo': "Get your task what will help you to manage your farming",
      'task_reminder_crop_name': "Crop Name",
      'task_reminder_pdate': "Plantation Date",
      'task_reminder_edate': "Event Duration",

      'advisory_title': "Advisory Bulletin",
      'advisory_promo': "To get updated ,explore the bulletins.You will get bulletins by different category",
      'advisory_current': "Current",
      'advisory_archive': "Archive",
      'advisory_select_district': "Select District"

    },
    'bn_BD': {
      'title': 'বামিস',

      'tab_home': 'হোম',
      'tab_agri': 'এগ্রি-হাব',
      'tab_community': 'জনসাধারণ',
      'tab_profile': 'প্রোফাইল',

      'dashboard': 'ড্যাশবোর্ড',
      'dashboard_today_weather': 'আজকের আবহাওয়া',
      'dashboard_rainfall': 'বৃষ্টিপাত',
      'dashboard_humidity': 'আর্দ্রতা',
      'dashboard_wind': 'বাতাসের গতি',
      'dashboard_take_a_look': 'একবার দেখে নিন',
      'dashboard_my_crops': 'আমার ফসল',
      'dashboard_view_all': 'সবগুলো দেখুন',
      'dashboard_weather_forecast': 'আবহাওয়া\nপূর্বাভাস',
      'dashboard_weather_alert': 'আবহাওয়া\nসতর্কবার্তা',
      'dashboard_flood_forecast': 'বন্যা\nপূর্বাভাস',
      'dashboard_crop_advisory': 'ফসল\nপরামর্শ',
      'dashboard_pest_disease': 'রোগের\nসতর্কতা',
      'dashboard_pest_disease_information': 'রোগের\nতথ্য',
      'dashboard_task_reminder': 'টাস্ক\nরিমাইন্ডার',
      'dashboard_advisory_bulletin': 'এডভাইজারি\nবুলেটিন',
      'dashboard_online_library': 'অনলাইন\nলাইব্রেরি',
      'dashboard_farm_metrics': 'ফার্ম\nমেট্রিক্স',
      'dashboard_stage_status': 'ধাপের অবস্থা',
      'dashboard_plantation': 'রোপন',
      'dashboard_stage_duration': 'ধাপের মেয়াদ',
      'dashboard_no_crops_found': 'আপনি এখনও কোন ফসল যুক্ত করেন নাই!',
      'dashboard_special_bulletin': 'বিশেষ বুলেটিন',
      'dashboard_mycrops_promo': "আপনি এখনও কোনো ফসল যোগ করেননি!",
      'dashboard_time_good_morning': "শুভ সকাল",
      'dashboard_time_good_noon': "শুভ দুপুর",
      'dashboard_time_good_afternoon': "শুভ বিকাল",
      'dashboard_time_good_evening': "শুভ সন্ধা",
      'dashboard_time_good_night': "শুভ রাত্রি",
      'dashboard_sidebar_important_video': "গুরুত্বপূর্ণ ভিডিও",
      'dashboard_sidebar_contact_us': "যোগাযোগ করুণ",
      'dashboard_sidebar_faq': "এফএকিউ ",
      'dashboard_sidebar_logout': "লগ আউট",
      'dashboard_snack_one_title': "সতর্কতা",
      'dashboard_snack_one_message': "এই পর্যায়টি এখনও শুরু হয়নি। এই পর্যায়টি প্রদর্শিত হওয়া পর্যন্ত অপেক্ষা করুন।",
      'learn_more': "বিস্তারিত জানুন >",


      'weather_forecast': 'আবহাওয়া পূর্বাভাস',
      'wf_title': 'আবহাওয়া পূর্বাভাস',
      'wf_subtitle': 'পরবর্তী ১০ দিনের আবহাওয়া পূর্বাভাস',
      'wf_temp': 'তাপমাত্রা',
      'wf_rf': 'বৃষ্টিপাত',
      'wf_rh': 'আপেক্ষিক আর্দ্রতা',
      'wf_wind': 'বাতাসের গতি',

      'weather_alert': 'আবহাওয়া সতর্কবার্তা',
      'flood_forecast': 'বন্যা পূর্বাভাস',

      'all_application': "সকল এপ্লিকেশন",

      'profile': 'প্রোফাইল',
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল বিত্রান্ত',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল এড্রেস',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল ইনফো হালনাগাদ করুণ',
      'profile_language': 'ভাষা',
      'profile_language_select': 'ভাষা নির্বাচন করুণ',
      'profile_logout': 'লগ আউট',
      'profile_logout_text': 'তুমি কী প্রস্থান করতে চাও? আমাদের আবার দেখা হবে তুমি যখন ফিরে আসবে।',

      'elibrary_title': 'অনলাইন লাইব্রেরি',

      'scan': 'স্ক্যান করুন',
      'title': 'রোগ নির্ণয় করুন',
      'wait': 'অনুগ্রহ পূর্বক অপেক্ষা করুন...',
      'select_crop': 'ফসল নির্বাচন করুন',
      'select_photo': 'কোন ছবি নির্বাচন করা হয়নি, অনুগ্রহ করে একটি ছবি ক্যামেরা অথবা গ্যালারি থেকে নির্বাচন করুন!',
      'detect_disease_pest': 'রোগ এবং কীটপতঙ্গ সনাক্ত করুন',
      'disease_name': 'রোগের নাম',
      'scientific_name': 'বৈজ্ঞানিক নাম',
      'pathogen': 'অনুজীব',
      'virus': 'ভাইরাস',
      'bacteria': 'ব্যাকটেরিয়া',
      'deficiency': 'ঘাটতি',
      'additional': 'অতিরিক্ত',
      'fungi': 'ছত্রাক',
      'insect': 'পোকা',
      'mite': 'ক্ষুদ্র পরজীবী',
      'weed': 'আগাছা',
      'others': 'অন্যান্য',
      'can_also_found': 'পাওয়া যেতে পারে',
      'potato': "আলু",
      'tomato': "টমেটো",
      'rice': "ধান",
      'preventive_measures': "প্রতিরোধমূলক ব্যবস্থা",
      'symptoms': "উপসর্গ",
      'symptoms_short': "সংক্ষিপ্ত উপসর্গ",
      'treatment_chemical': "রাসায়নিক চিকিত্সা",
      'treatment_organic': "জৈব চিকিত্সা",
      'trigger': "কিভাবে ছড়ায়",

      'add_mycrop_title': "নতুন ফসল যুক্ত করুণ",
      'add_mycrop_select_crop': "ফসল নির্বাচন করুণ",
      'add_mycrop_select_location': "স্থান নির্বাচন করুণ",
      'add_mycrop_select_plantation_date': "ফসল লাগানোর তারিখ নির্বাচন করুণ",
      'add_mycrop_submit': "নতুন ফসল যুক্ত করুণ",
      'add_mycrop_delete': "মুছে ফেলুন",

      'mycrop_advisory_title': "ফসল পরামর্শ",
      'mycrop_advisory_promo': "নির্দিষ্ট পরামর্শ পেতে নির্দিষ্ট ফসল নির্বাচন করুন",
      'mycrop_advisory_stage_title': "ফসলের ধাপ অনুযায়ী পরামর্শ",
      'mycrop_advisory_stage_promo': "প্রতিটি ধাপের জন্য পরামর্শ",
      'mycrop_disease_title': "ফসলের রোগ",
      'mycrop_disease_promo': "নির্দিষ্ট রোগের পরামর্শ পেতে নির্দিষ্ট ফসল নির্বাচন করুন",
      'mycrop_disease_stage_title': "ফসলের ধাপ অনুযায়ী রোগের পরামর্শ",
      'mycrop_disease_stage_promo': "প্রতিটি ধাপের জন্য ফসলের রোগের পরামর্শ",

      'community_title': "জনসাধারণ",
      'community_promot': "BAMIS কমিউনিটিতে স্বাগতম",
      'community_post_add_title': "নতুন কমিউনিটি পোস্ট যুক্ত করুণ",

      'agrihub_get_cultivation_tips': "চাষের পরামর্শ পেতে ক্লিক করুণ",

      'pda_title': 'পোকামাকড় ও রোগের তথ্য',
      'pda_select_crop': 'ফসল নির্বাচন করুন',
      'pda_view_all': 'সবগুলো দেখুন',
      'pda_scientific_name': 'বৈজ্ঞানিক নাম',
      'pda_pathogen_name': 'জীবাণুর নাম',
      'pda_symptoms': 'লক্ষণ',
      'pda_preventive_measure': 'প্রতিরোধমূলক ব্যবস্থা',
      'pda_organic_control': 'জৈব নিয়ন্ত্রণ',
      'pda_chemical_control': 'রাসায়নিক নিয়ন্ত্রণ',
      'pda_what_caused_it': 'এটার কারণ কী?',

      'notification_title': "বিজ্ঞপ্তি",

      'task_reminder_title': "টাস্ক রিমাইন্ডার",
      'task_reminder_promo': "তোমার কৃষিকাজ পরিচালনা করতে সাহায্য করবে এমন কাজগুলো দেয়া হলো।",
      'task_reminder_crop_name': "ফলসের নাম",
      'task_reminder_pdate': "রোপণের তারিখ",
      'task_reminder_edate': "কাজের সময়কাল",

      'advisory_title': "অ্যাডভাইসরি বুলেটিন",
      'advisory_promo': "আপডেট পেতে, বুলেটিনগুলি অনুসন্ধান করুন। আপনি বিভিন্ন বিভাগ অনুসারে বুলেটিন পেতে পারেন।",
      'advisory_current': "চলমান",
      'advisory_archive': "সংরক্ষণকৃত",
      'advisory_select_district': "জেলা নির্বাচন করুণ"
    }
  };
}