import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'Bamis',

      'tab_home': 'Home',
      'tab_agri': 'Agri-Hub',
      'tab_community': 'Community',
      'tab_profile': 'Profile',

      'dashboard': 'Dashboard',
      'dashboard_today_weather': 'Today\'s Weather',
      'dashboard_rainfall': 'Rainfall',
      'dashboard_humidity': 'Humidity',
      'dashboard_wind': 'Wind Speed',
      'dashboard_take_a_look': 'Take a look',
      'dashboard_my_crops': 'MY CROPS',
      'dashboard_view_all': 'View All',
      'dashboard_weather_forecast': 'Weather\nForecast',
      'dashboard_weather_alert': 'Weather\nAlert',
      'dashboard_flood_forecast': 'Flood\nForecast',
      'dashboard_crop_advisory': 'Crop\nAdvisory',
      'dashboard_pest_disease': 'Pest & Disease\nAlert',
      'dashboard_task_reminder': 'Task\nReminder',
      'dashboard_advisory_bulletin': 'Advisory\nBulletin',
      'dashboard_online_library': 'Online\nLibrary',
      'dashboard_farm_metrics': 'Farm\nMetrics',
      'dashboard_stage_status': 'Stage Status',
      'dashboard_plantation': 'Plantation',
      'dashboard_stage_duration': 'Stage Duration',
      'dashboard_no_crops_found': 'You did not add any crops yet!',
      'dashboard_special_bulletin': 'Special Bulletin',

      'weather_alert': 'Weather Alert',
      'flood_forecast': 'Flood Forecast',

      'profile': 'Profile',
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_language': 'Language',
      'profile_language_select': 'Select Language',
      'profile_logout': 'Logout',
      'profile_logout_text': 'Logging out? We will be here when you are back!',

      'elibrary_title': 'Online Library',

      'scan': 'Scan',
      'title': 'Disease Detection',
      'wait': 'Please wait...',
      'select_crop': 'Select Crop',
      'select_photo': 'No photo selected, Please select or capture one phone!',
      'detect_disease_pest': 'Detect Disease & Pest',
      'disease_name': 'Disease Name',
      'scientific_name': 'Scientific Name',
      'pathogen': 'Pathogen',
      'virus': 'Virus',
      'bacteria': 'Bacteria',
      'deficiency': 'Deficiency',
      'additional': 'Additional',
      'fungi': 'Fungi',
      'insect': 'Insect',
      'mite': 'Mite',
      'weed': 'Weed',
      'others': 'Others',
      'can_also_found': 'Can also be found in',
      'potato': "Potato",
      'tomato': "Tomato",
      'rice': "Rice",
      'preventive_measures': "Preventive Measures",
      'symptoms': "Symptoms",
      'symptoms_short': "Symptoms Short",
      'treatment_chemical': "Treatment Chemical",
      'treatment_organic': "Treatment Organic",
      'trigger': "Trigger",

      'add_mycrop_title': "Add New Crop",
      'add_mycrop_select_crop': "Select Crop",
      'add_mycrop_select_location': "Select Location",
      'add_mycrop_select_plantation_date': "Select Plantation Date",
      'add_mycrop_submit': "Add New Crop",
    },
    'bn_BD': {
      'title': 'বামিস',

      'tab_home': 'হোম',
      'tab_agri': 'এগ্রি-হাব',
      'tab_community': 'জনসাধারণ',
      'tab_profile': 'প্রোফাইল',

      'dashboard': 'ড্যাশবোর্ড',
      'dashboard_today_weather': 'আজকের আবহাওয়া',
      'dashboard_rainfall': 'বৃষ্টিপাত',
      'dashboard_humidity': 'আর্দ্রতা',
      'dashboard_wind': 'বাতাসের গতি',
      'dashboard_take_a_look': 'একবার দেখে নিন',
      'dashboard_my_crops': 'আমার ফসল',
      'dashboard_view_all': 'সবগুলো দেখুন',
      'dashboard_weather_forecast': 'আবহাওয়া\nপূর্বাভাস',
      'dashboard_weather_alert': 'আবহাওয়া\nসতর্কবার্তা',
      'dashboard_flood_forecast': 'বন্যা\nপূর্বাভাস',
      'dashboard_crop_advisory': 'ফসল\nপরামর্শ',
      'dashboard_pest_disease': 'কীটপতঙ্গ ও রোগের\nসতর্কতা',
      'dashboard_task_reminder': 'টাস্ক\nরিমাইন্ডার',
      'dashboard_advisory_bulletin': 'এডভাইজারি\nবুলেটিন',
      'dashboard_online_library': 'অনলাইন\nলাইব্রেরি',
      'dashboard_farm_metrics': 'ফার্ম\nমেট্রিক্স',
      'dashboard_stage_status': 'ধাপের অবস্থা',
      'dashboard_plantation': 'রোপন',
      'dashboard_stage_duration': 'ধাপের মেয়াদ',
      'dashboard_no_crops_found': 'আপনি এখনও কোন ফসল যুক্ত করেন নাই!',
      'dashboard_special_bulletin': 'বিশেষ বুলেটিন',

      'weather_alert': 'আবহাওয়া সতর্কবার্তা',
      'flood_forecast': 'বন্যা পূর্বাভাস',

      'profile': 'প্রোফাইল',
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল বিত্রান্ত',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল এড্রেস',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল ইনফো হালনাগাদ করুণ',
      'profile_language': 'ভাষা',
      'profile_language_select': 'ভাষা নির্বাচন করুণ',
      'profile_logout': 'লগ আউট',
      'profile_logout_text': 'তুমি কী প্রস্থান করতে চাও? আমাদের আবার দেখা হবে তুমি যখন ফিরে আসবে।',

      'elibrary_title': 'অনলাইন লাইব্রেরি',

      'scan': 'স্ক্যান করুন',
      'title': 'রোগ নির্ণয় করুন',
      'wait': 'অনুগ্রহ পূর্বক অপেক্ষা করুন...',
      'select_crop': 'ফসল নির্বাচন করুন',
      'select_photo': 'কোন ছবি নির্বাচন করা হয়নি, অনুগ্রহ করে একটি ছবি ক্যামেরা অথবা গ্যালারি থেকে নির্বাচন করুন!',
      'detect_disease_pest': 'রোগ এবং কীটপতঙ্গ সনাক্ত করুন',
      'disease_name': 'রোগের নাম',
      'scientific_name': 'বৈজ্ঞানিক নাম',
      'pathogen': 'অনুজীব',
      'virus': 'ভাইরাস',
      'bacteria': 'ব্যাকটেরিয়া',
      'deficiency': 'ঘাটতি',
      'additional': 'অতিরিক্ত',
      'fungi': 'ছত্রাক',
      'insect': 'পোকা',
      'mite': 'ক্ষুদ্র পরজীবী',
      'weed': 'আগাছা',
      'others': 'অন্যান্য',
      'can_also_found': 'পাওয়া যেতে পারে',
      'potato': "আলু",
      'tomato': "টমেটো",
      'rice': "ধান",
      'preventive_measures': "প্রতিরোধমূলক ব্যবস্থা",
      'symptoms': "উপসর্গ",
      'symptoms_short': "সংক্ষিপ্ত উপসর্গ",
      'treatment_chemical': "রাসায়নিক চিকিত্সা",
      'treatment_organic': "জৈব চিকিত্সা",
      'trigger': "কিভাবে ছড়ায়",

      'add_mycrop_title': "নতুন ফসল যুক্ত করুণ",
      'add_mycrop_select_crop': "ফসল নির্বাচন করুণ",
      'add_mycrop_select_location': "স্থান নির্বাচন করুণ",
      'add_mycrop_select_plantation_date': "ফসল লাগানোর তারিখ নির্বাচন করুণ",
      'add_mycrop_submit': "নতুন ফসল যুক্ত করুণ",

    }
  };
}