part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const WEATHER_FORECAST = _Paths.WEATHER_FORECAST;
  static const WEATHER_ALERT = _Paths.WEATHER_ALERT;
  static const FLOOD_FORECAST = _Paths.FLOOD_FORECAST;
  static const WEBVIEW = _Paths.WEBVIEW;
  static const ELIBRARY = _Paths.ELIBRARY;
  static const PDFVIEW = _Paths.PDFVIEW;
  static const BULLETINS = _Paths.BULLETINS;
  static const CROP_ADVISORY = _Paths.CROP_ADVISORY;
  static const PEST_DISEASE_ALERTS = _Paths.PEST_DISEASE_ALERTS;
  static const FARM_METRICS = _Paths.FARM_METRICS;
  static const TASK_REMINDER = _Paths.TASK_REMINDER;
  static const COMMUNITY_POST_DETAIL = _Paths.COMMUNITY_POST_DETAIL;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const BULLETIN_NATIONAL = _Paths.BULLETIN_NATIONAL;
  static const BULLETIN_DISTRICT = _Paths.BULLETIN_DISTRICT;
  static const BULLETIN_SPECIAL = _Paths.BULLETIN_SPECIAL;
  static const IMPORTANT_VIDEO = _Paths.IMPORTANT_VIDEO;
  static const CONTACT_US = _Paths.CONTACT_US;
  static const FAQ = _Paths.FAQ;
  static const ARTICLES = _Paths.ARTICLES;
  static const YTPLAYER = _Paths.YTPLAYER;
  static const SCAN_DETAIL = _Paths.SCAN_DETAIL;
  static const PEST_DISEASE_ALERT_DETAIL = _Paths.PEST_DISEASE_ALERT_DETAIL;
  static const MYCROP = _Paths.MYCROP;
  static const MYCROP_ADD = _Paths.MYCROP_ADD;
  static const CROP_ADVIOSRY_STAGES = _Paths.CROP_ADVIOSRY_STAGES;
  static const CROP_ADVIOSRY_STAGE_DETAIL = _Paths.CROP_ADVIOSRY_STAGE_DETAIL;
  static const CROP_DISEASE = _Paths.CROP_DISEASE;
  static const CROP_DISEASE_STAGES = _Paths.CROP_DISEASE_STAGES;
  static const CROP_DISEASE_STAGES_DETAIL = _Paths.CROP_DISEASE_STAGES_DETAIL;
  static const ALL_MODULE = _Paths.ALL_MODULE;
  static const COMMUNITY_POST_ADD = _Paths.COMMUNITY_POST_ADD;
  static const COMMUNITY_POST_MY = _Paths.COMMUNITY_POST_MY;
  static const TASK_REMINDER_DETAIL = _Paths.TASK_REMINDER_DETAIL;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const WEATHER_FORECAST = '/weather-forecast';
  static const WEATHER_ALERT = '/weather-alert';
  static const FLOOD_FORECAST = '/flood-forecast';
  static const WEBVIEW = '/webview';
  static const ELIBRARY = '/elibrary';
  static const PDFVIEW = '/pdfview';
  static const BULLETINS = '/bulletins';
  static const CROP_ADVISORY = '/crop-advisory';
  static const PEST_DISEASE_ALERTS = '/pest-disease-alerts';
  static const FARM_METRICS = '/farm-metrics';
  static const TASK_REMINDER = '/task-reminder';
  static const COMMUNITY_POST_DETAIL = '/community-post-detail';
  static const NOTIFICATIONS = '/notifications';
  static const BULLETIN_NATIONAL = '/bulletin-national';
  static const BULLETIN_DISTRICT = '/bulletin-district';
  static const BULLETIN_SPECIAL = '/bulletin-special';
  static const IMPORTANT_VIDEO = '/important-video';
  static const CONTACT_US = '/contact-us';
  static const FAQ = '/faq';
  static const ARTICLES = '/articles';
  static const YTPLAYER = '/ytplayer';
  static const SCAN_DETAIL = '/scan-detail';
  static const PEST_DISEASE_ALERT_DETAIL = '/pest-disease-alert-detail';
  static const MYCROP = '/mycrop';
  static const MYCROP_ADD = '/mycrop-add';
  static const CROP_ADVIOSRY_STAGES = '/crop-adviosry-stages';
  static const CROP_ADVIOSRY_STAGE_DETAIL = '/crop-adviosry-stage-detail';
  static const CROP_DISEASE = '/crop-disease';
  static const CROP_DISEASE_STAGES = '/crop-disease-stages';
  static const CROP_DISEASE_STAGES_DETAIL = '/crop-disease-stages-detail';
  static const ALL_MODULE = '/all-module';
  static const COMMUNITY_POST_ADD = '/community-post-add';
  static const COMMUNITY_POST_MY = '/community-post-my';
  static const TASK_REMINDER_DETAIL = '/task-reminder-detail';
}
